### ISSUE TITLE
Network graph not shown

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#1]
I wrote a small program trying to load a simple gene network, but the web page only shows a horizontal bar in color (see attached screenshot).
[d3-network-test](https://cloud.githubusercontent.com/assets/15133253/18355129/33ad80d0-75b6-11e6-9ced-68200a9c8e03.png)

Here is the javascript code that I wrote:

```
<script type="text/javascript">
     genes_in = [
         { id: 0, name: "zero" },
         { id: 1, name: "one" },
         { id: 2, name: "two" },
         { id: 3, name: "three" }
     ];

     edges_in = [
         { source: 0, target: 1, weight: 0.1 },
         { source: 0, target: 2, weight: 0.2 },
         { source: 0, target: 3, weight: 0.3 },
         { source: 1, target: 2, weight: 0.4 },
         { source: 2, target: 3, weight: 0.5 }
     ];

     var network = d3.network().genes(genes_in).edges(edges_in);
     d3.select("#chart").append("svg").attr("width", 500).attr("height", 500).call(network);
     network.showLegend().filter(.05, 10).draw();
</script>
```

The console of Chrome's development tools shows many errors like this:

```
d3.v2.js:1614 Error: <line> attribute x1: Expected length, "NaN".
```

which points to lines 171-173 of **d3.network.js**. 
(**d3.v2.js** is the d3 library that I downloaded from your GIANT web server.)

Can you tell me where I did wrong? Thanks.

**Comment by dongbohu** [comment]
I uploaded a screenshot file. The original pdf file didn't show the horizontal bar correctly.

**Comment by aaronkw** [comment]
Try the latest commit  -- degree calculation assumed that the network is fully connected (there's always an edge to the query), which is the case for our functional networks but definitely not always true.

**Comment by aaronkw** [comment]
Oh also, try this to display the gene names:

``` js
d3.network().genes(genes_in).edges(edges_in).geneText('name');
```

The default variable name to display is 'standard_name' but can be customized.

**Comment by dongbohu** [comment]
Thank you for your reply. I added `geneText('name')`, but the web page looks the same (with the same errors on the console).

**Comment by aaronkw** [comment]
Actually, geneText takes a function (my mistake). Here's a git gist of what I'm seeing:
https://bl.ocks.org/aaronkw/88d2cfb7329418200fe5c5ae588275f5

**Comment by dongbohu** [comment]
Thank you. I tried your code and it works!

**Comment by aaronkw** [comment]
Can I add your example to the main page? Having a toy example is a good idea!

**Comment by aaronkw** [comment]
Also, if you want to use d3 v3, the links require an id field:

https://bl.ocks.org/aaronkw/5ab0840151369a7217f6f8400f5ca91b/62825f9f305dbb474ff7b8c30e9ea85cf1230932

**Comment by dongbohu** [comment]
Of course, please feel free to add the example to the main page. I am sure it will be helpful to other users too.
