### ISSUE TITLE
Support of Negative Edge Weight

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#10]
You may remember that the edge weight values in the app that I have been working on are in the range of (-1.0, 1.0). In order to use d3.network, I have to manually translate these values into the range of (0, 2.0). The code is not natural and involves lots of weight conversions back and forth. So I would like to extend d3.network so that it can support negative weight officially. 

I have checked the code and this feature is not as complicated to implement as I thought. Do you mind if I change the code and file a PR for you to review?

**Comment by aaronkw** [comment]
Sure, that sounds fine to me!
