### ISSUE TITLE
"source" and "target" Properties in Edge

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#2]
On lines 52-53 of **d3.network.js**: 

```
if (typeof edge.source == "number") edge.source = genes[edge.source];
if (typeof edge.target == "number") edge.target = genes[edge.target];
```

The code seems to be assuming that each input edge's **source** and **target** properties are identical to the source and target gene's index in input genes. This may not be the case if genes and edges are retrieved from a back end database. For example, suppose we have the following input data:

```
genes_in = [ { id: 123, name: "foo" }, { id: 456, name: "bar" } ];
edges_in = [ { source: 123, target: 456, weight: 3.14} ];
```

The program will crash due to the out-of-range error in the above two lines.

It seems to make more sense if we change lines 52-53 into something like:

```
function search_gene_by_id(id_in) {
  for (var idx = 0; idx < genes.length; ++idx) {
      if (genes[idx] === id_in) return genes[idx];
  }
  return undefined; // optional line
}
if (typeof edge.source == "number") edge.source = search_gene_by_id(edge.source);
if (typeof edge.target == "number") edge.target = search_gene_by_id(edge.target);
```

**Comment by aaronkw** [comment]
Did your message get clipped?

**Comment by dongbohu** [comment]
Sorry, I submitted the issue by accident before I finished it. I have updated it.

**Comment by aaronkw** [comment]
I see your point! So actually I did this to follow the d3 convention. According to the documentation, the values of 'source' and 'target' may be initialized with the index of the node in the node array (and in fact our backend remaps the ids to accommodate this):

> Note: the values of the source and target attributes may be initially specified as indexes into the nodes array; these will be replaced by references after the call to start. Link objects may have additional fields that you specify; this data can be used to compute link strength and distance on a per-link basis using an accessor function.

[Reference](https://github.com/d3/d3-3.x-api-reference/blob/master/Force-Layout.md)

The d3 force layout code actually does this exact binding: 

``` javascript
      for (i = 0; i < m; ++i) {
        o = links[i];
        if (typeof o.source == "number") o.source = nodes[o.source];
        if (typeof o.target == "number") o.target = nodes[o.target];
        ++o.source.weight;
        ++o.target.weight;
      }
```

I bind the nodes explicitly because I need it before the force layout.

**Comment by aaronkw** [comment]
My suggested would be to follow the d3 convention so that everything binds correctly and use a different field if you want to store the database id. Otherwise you have to do custom binding.

```js
genes_in = [ { id: 0, name: "foo", db_id: 123 }, { id: 1, name: "bar", db_id:456 } ];
edges_in = [ { source: 0, target: 1, weight: 3.14} ];
```

**Comment by aaronkw** [comment]
Also, note that the only thing you would have to change is this:

``` js
genes_in = [ { id: 123, name: "foo" }, { id: 456, name: "bar" } ];
edges_in = [ { source: 0, target: 1, weight: 3.14} ];
```

**Comment by dongbohu** [comment]
I got it. Thank you very much for the clarification.
