### ISSUE TITLE
Customize the starting and ending values of legend and its text

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#3]
Is there an easy way to change the starting and ending values of the legend? Right now the values are always in the range of **0~1.0**, but our gene network edges have weight of **-1.0~1.0**.

It will be nice if you can add another utility function such as `addLegendTxt(string)` to set the legend text underneath the bar.

Thanks.

**Comment by aaronkw** [comment]
That should be easy to do -- I'll add that sometime this week.

**Comment by dongbohu** [comment]
Thank you very much.

**Comment by dongbohu** [comment]
I just realized that when the edge's weight is negative, the code may have to be modified more than I expected. The whole implementation of d3.network is assuming that `weight` will be always positive. The thickness of each edge on the UI and the source/target degrees all depend on weight's value.

In the example that we wrote together:
https://bl.ocks.org/aaronkw/5ab0840151369a7217f6f8400f5ca91b
if we change the first edge's weight from **0.1** to **-0.4**, and set the edge_cut to **-1.0**:

```
network.showLegend().filter(-1.0, 5).draw();
```

The program will crash.

**Comment by aaronkw** [comment]
One option is to rescale on the fly -- scale from 0 to 2 internally, but -1 to 1 when displaying the edge weight.

**Comment by dongbohu** [comment]
Yes, that is a great idea. I will do that. Thanks.

**Comment by dongbohu** [comment]
Any progress on the new feature? Thanks.

**Comment by aaronkw** [comment]
Sorry for the delay -- I'll add it today

**Comment by dongbohu** [comment]
Thanks. Really appreciate your help!

**Comment by aaronkw** [comment]
Try the latest commit -- some of the spacing might be off if you choose a different font size. I should probably try to detect font rendering sizes but it's more of a pain.

**Comment by dongbohu** [comment]
Thank you.  I will try it.

**Comment by aaronkw** [comment]
Here's an example gist: https://bl.ocks.org/aaronkw/d93b1fc0cf8435c8851ad426fec4ec0b

**Comment by dongbohu** [comment]
Can you also add the feature of customizing the starting and ending values of the legend?

**Comment by aaronkw** [comment]
I added `legendStart(-1)` and `legendEnd(1)` functions

**Comment by dongbohu** [comment]
Nice! Thank you again.

**Comment by dongbohu** [comment]
I re-scaled the edge weight from the range of (-1.0, 1.0) to (0, 2.0), but now the color of each edge is not correct (because the color corresponds to the re-scaled weight on the legend bar, not the original weight). Do you think there is an easy way to make the color consistent without modifying internal implementation of d3.network? Thanks.

**Comment by aaronkw** [comment]
Is this using a custom color function?

**Comment by dongbohu** [comment]
No, I am not using any color function.

**Comment by aaronkw** [comment]
Ahh, you could pass in a custom color function `edgeColor(color)` where color is a function that handles the logic of mapping back to (-1.0, 1.0) from (0, 2.0). Would that work?

**Comment by dongbohu** [comment]
I tried this:

```
network.legendText("Correlation").legendStart(-1).legendEnd(1.0).edgeColor(function(x) { return x + 1.0; }).showLegend().draw();
```

But now the color bar is all black, and the svg shows only node circles w/o any edges.

**Comment by aaronkw** [comment]
You actually need to pass a d3 range function like this:

``` javascript
 var edgeColor = d3.scale.linear().domain([options.start_edge,.15,1])
        .range([options.start_color, options.mid_color, options.end_color]);
```

**Comment by aaronkw** [comment]
in your case it would be 

``` javascript
network.legendText("Correlation").legendStart(-1).legendEnd(1.0).setEdgeColor(d3.scale.linear().domain([0,1,2]).range(['green', 'orange', 'red']))
```

**Comment by dongbohu** [comment]
Thank you for the update. But the edge color still doesn't seem to be correct. The input genes and edges are:

```
genes_in = [
  { id: 0, name: "zero" },
  { id: 1, name: "one" },
  { id: 2, name: "two"},
  { id: 3, name: "three", query:true}
];

edges_in = [
  { id: 0, source: 0, target: 1, weight: -0.9 },
  { id: 1, source: 0, target: 2, weight: -0.5 },
  { id: 2, source: 0, target: 3, weight: 0 },
  { id: 3, source: 1, target: 2, weight: 0.5 },
  { id: 4, source: 2, target: 3, weight: 0.9 }
];
```

After re-scaling, the edges become:

```
edges_in = [
  { id: 0, source: 0, target: 1, weight: 0.1 },
  { id: 1, source: 0, target: 2, weight: 0.5 },
  { id: 2, source: 0, target: 3, weight: 1.0 },
  { id: 3, source: 1, target: 2, weight: 1.5 },
  { id: 4, source: 2, target: 3, weight: 1.9 }
];
```

The color on the legend bar seems to show only the colors of left half (-1.0, 0), although it is marked correctly. Shouldn't the right-side color on the bar be red instead of orange?
(See the attached file.)
![network_09_30](https://cloud.githubusercontent.com/assets/15133253/18995766/a1bbe516-86fb-11e6-95b4-1c7ff7b42b66.png)

**Comment by aaronkw** [comment]
Ok, I had to add a couple of more functions. Here's the example gist: https://bl.ocks.org/aaronkw/8f16076d7eb76e78071df8c4c74c4e11

`minEdge()` and `maxEdge()` specify the min/max values of the edges (as input to d3)

`legendStart` and `legendEnd()` specify what text to display in the legend

**Comment by dongbohu** [comment]
Great! Thank you.

**Comment by dongbohu** [comment]
By the way, you can close this issue now, if you want.
