### ISSUE TITLE
"mouseclick" Event Listener on Gene Circle

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#4]
I tried to add a new listener for `mouseclick` event on the gene circle. Here is what added in the example:

```
function callback() {
  console.log("hello world");
}
network.onGene("mouseclick.custom", callback);
```

But I can't see the messages from console at all. Then I tried `mouseover` event on the edge and it worked. What is the proper way to register the mouseclick event on gene circle?

**Comment by aaronkw** [comment]
Try it again with the latest commit...

**Comment by dongbohu** [comment]
Thanks for the update. Now **mouseover** is working on gene circle now, but **mouseclick** is still not working on gene circle.

**Comment by dongbohu** [comment]
By the way, on line #138 of **README.md**, is the second "mouseout" supposed to be "mousedown" or some other mouse-related event name?

**Comment by aaronkw** [comment]
I think the documentation is wrong, it should be `onGene('click', callback)`

**Comment by aaronkw** [comment]
actually, nevermind, the documentation doesn't specify mouseclick!

**Comment by aaronkw** [comment]
`onGene` and `onEdge` are just wrappers for d3's `on`. The comprehensive list of actions is here: https://github.com/d3/d3-3.x-api-reference/blob/master/Selections.md#on

and https://developer.mozilla.org/en-US/docs/Web/Events#Standard_events

**Comment by dongbohu** [comment]
Thanks for the update. What I meant to say is that "mouseout" events are listed twice on line #138, and the second one should be either deleted or changed to something else.

**Comment by aaronkw** [comment]
ah yes, i'll update that sentence
