### ISSUE TITLE
Legend text configuration

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#5]
Is it possible to assign a class to the legend text so that users can configure it (like the **gene-name** class)? I tried to change the text size with this style:

```
text: {
    font-size: 13;
}
```

and it doesn't seem to have any effect.

But if I change d3.network.js to assign a class name to **legendStart**, **legendEnd** and **legendText** like this:

```
.attr("class", "legend-text")
```

and change CSS into:

```
text.legend-text: {
    font-size: 13;
}
```

then it works as expected. I wonder whether this is because **text** conflicts with other identifiers in bootstrap.

Another thing that bothers me is in my application code, the **legendEnd** text does not show up for some reason (see my attached image file). Do you have any idea why? 

Thanks again.
![gene_img](https://cloud.githubusercontent.com/assets/15133253/19742290/537c4d68-9b92-11e6-9b54-3f6156bd8448.png)

**Comment by aaronkw** [comment]
I probably won't have time this week, but if you submit a PR, I will review and integrate!

**Comment by dongbohu** [comment]
Sure. I will do that.
