### ISSUE TITLE
New feature request: Set both minimum and maximum edge cutoff values in filter() method

### ISSUE THREAD

**Issue by dongbohu** [aaronkw/d3-network#7]
I wonder whether you can add one more parameter in `filter()` method so that we can call it by either:
```
network.filter(min_edge_cut, node_cut);
```
or:
```
network.filter(min_edge_cut, max_edge_cut, node_cut);
```
Thanks.

**Comment by dongbohu** [comment]
If you prefer, I can do it and submit a pull request. Thanks.

**Comment by aaronkw** [comment]
Sure, that sounds good!
